# Generated by Django 5.2.6 on 2025-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_type',
            field=models.CharField(choices=[('human', 'Human Doctor'), ('vet', 'Veterinarian')], default='human', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
