# Generated by Django 5.2.6 on 2025-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcategory',
            options={'verbose_name_plural': 'Pet Categories'},
        ),
    ]
