# Generated by Django 5.2.6 on 2025-09-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_petcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcategory',
            options={},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pet_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.petproduct'),
        ),
    ]
