# Generated by Django 5.2.6 on 2025-09-30 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_petcategory_options_orderitem_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eLabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Pathology', 'Pathology'), ('Other', 'Other')], max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
