# Generated by Django 5.2.6 on 2025-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_elabschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='elabschedule',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='elab_reports/'),
        ),
    ]
