# Generated by Django 5.2.6 on 2025-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_elabschedule_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='elabschedule',
            name='report_verified',
            field=models.BooleanField(default=False),
        ),
    ]
