# Generated by Django 5.2.6 on 2025-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_elabschedule_report_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='elabschedule',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='elabschedule',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
