# Generated by Django 5.2.6 on 2025-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_elabschedule_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elabschedule',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
