# Generated by Django 5.2.6 on 2025-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_elabschedule_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elabschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='elabschedule',
            name='test_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
