# Generated by Django 5.1.3 on 2025-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_elabschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elabschedule',
            name='test_type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Pathology', 'Pathology')], max_length=100),
        ),
    ]
